fadeIn() now uses opacity to figure out the final opacity to fade into
replit/kaboom pull request #844
Opened 2024-04-06 14:20 UTC by niceEli

Changed fadeIn to use opacity so it can fade into 0.5 for example
Changed Contributing.md because there was "" around linebreak style and that isnt correct
Added fadeIn example so you can learn fadeIn
Changed JSDoc to have a fadeIn example

2024-04-07 16:18 UTC, lajbel requested changes

2024-04-07 16:18 UTC, lajbel commented on examples/fadeIn.js
I am not convinced by the example. I feel it explains basic things and does not focus on fadeIn.

2024-04-07 16:18 UTC, lajbel commented on src/types.ts
I feel that all components are overexplained again, you have to get to the point.

2024-04-07 16:44 UTC, niceEli commented on examples/fadeIn.js
fixed. now updating PR

2024-04-07 16:44 UTC, niceEli commented on src/types.ts
fixed. now updating PR

2024-04-07 16:48 UTC, niceEli commented
no clue how to rebase so ill close and make a new PR

2024-04-07 16:54 UTC, niceEli commented
nvm turns out it auto rebases ig

2024-04-07 22:52 UTC, lajbel approved these changes
Is looking good

2024-05-07 22:50 UTC, reimertz commented
this would be a welcome addition! Was just trying to figure out how to do this.

2024-05-07 23:37 UTC, lajbel commented
can you add a changelog for this before merge?

2024-05-08 08:46 UTC, reimertz commented
@lajbel you mean me? I can fork this and create a new PR if you want.

Should add changes under version `v3000.2.1`? if So

```
## v3000.2.1
- fixed `fadeIn()` not properly using `opacity()`
```

Also, would this be considered a breaking change since all users who specify `opacity()`, then `fadeIn()` now will see the opacity actually being applied.

2024-05-08 12:54 UTC, lajbel commented
I was referring to the PR owner, but thank you! Good point

2024-05-08 12:54 UTC, merged